# This workflow will check the dependencies with OWASP

name: OWASP Dependency Checker - FEATURE BRANCH

on:
  push:
    branches:
      - 'dependabot/maven/org.owasp-dependency-check-maven-*'

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-owasp-${{ github.ref_name }}
      - name: Run OWASP Dependency Checker
        run: |
          mvn --file pom.xml --batch-mode \
            dependency-check:check -P vuln-check
      - name: Upload dependency report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.4.0
        with:
          name: dep-report-feature-branch
          path: target/dependency-check-report.html
